version: '3.8'

services:
  server:
    build:
      context: .
    container_name: backend-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      CORS_ORIGIN: "*"
      DB_SERVER: db
      DB_DATABASE: FeedMate
      DB_USER: collectifyuser
      DB_PASSWORD: StrongPassword123
      DB_ENCRYPT: "false"
      
      JWT_SECRET: "replace_me_with_random_string"
      JWT_EXPIRES_IN: "7d"
      IMAGEKIT_PUBLIC_KEY: "public_ZcxqHZs5/S3d5LiA4azg4iECyso="
      IMAGEKIT_PRIVATE_KEY: "private_omp0lb1TvJryOppRLDwXLAVJCoQ="
      IMAGEKIT_URL_ENDPOINT: "https://ik.imagekit.io/auvytqd1w"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-1
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123!" 
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    entrypoint: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 15; 
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'StrongPassword123!' -C -i /docker-entrypoint-initdb.d/init.sql; 
      wait"

    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'StrongPassword123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

volumes:
  mssql-data: